name: naiki_app
description: "NaikiApp - Localized Food & Resource Surplus Connector"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  firebase_database: ^11.0.0
  firebase_messaging: ^15.0.0
  shared_preferences: ^2.2.2

  # State Management
  provider: ^6.1.2

  # Location and Maps
  geolocator: ^11.0.0
  google_maps_flutter: ^2.6.0

  # UX / Utility
  flutter_local_notifications: ^17.0.0
  intl: ^0.19.0
  google_fonts: ^6.2.1
  cached_network_image: ^3.3.1
  permission_handler: ^11.3.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true